image: atlassian/default-image:3, gradle:8.5

definitions:
   services:
      docker:
         memory: 3072
pipelines:
  branches:
    master:
      - step:
          name: Build and Test
          script:
            - gradle build
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - gradle
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Deploy to Production
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION=${BITBUCKET_BUILD_NUMBER}
            - IMAGE=${DOCKERHUB_NAMESPACE}/${DOCKER_IMG_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}"
            - docker push "${IMAGE}"
            - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
            - docker push "${IMAGE}:${VERSION}"
          services:
            - docker