version: "1"

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_codecrafters
      MYSQL_ROOT_PASSWORD: root

  springboot-app:
    container_name: spring-app
    restart: always
    image: springboot-app
    build: .
    ports:
      - "9090:9000"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

