spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3307/db_codecrafters
    username: root
    password: root123
  sql:
    init:
      platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9000